--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Terpz710/MineconomyScoreTag
build-by-default: true
branches:
- main
projects:
  MineconomyScoreTag:
    path: ""
    phpstan: false
    lint: false
...
